import type { ProfileConfig } from "./schema";

export const brazyProfile: ProfileConfig = {
  version: 1,
  identity: {
    username: "brazy",
    displayName: "brazy",
    bio: "the most customizable bio on the internet.\nyour music, your vibe, your way.",
    avatarUrl: "https://i.pravatar.cc/300?u=brazy",
    tagline: "founder · designer",
    pronouns: "they/them",
    location: "brazy.it",
    verified: true,
    bioMarkdown: false,
  },
  theme: {
    mode: "dark",
    primaryColor: "#a855f7",
    secondaryColor: "#7c3aed",
    accentColor: "#c084fc",
    textColor: "#e9d5ff",
    mutedTextColor: "#71717a",
    backgroundColor: "#08070d",
    fontFamily: "geist",
    fontFamilyUrl: "",
    cardStyle: "glass",
    cardOpacity: 0.4,
    cardBlur: 20,
    borderRadius: 22,
    borderWidth: 1,
    glow: true,
    glowIntensity: 40,
    maxWidth: 440,
    contentAlign: "center",
    backgroundImage: "",
    backgroundOverlayColor: "#000000",
    backgroundOverlayOpacity: 0.5,
    animatedBorder: false,
    motionProfile: "balanced",
    profileSize: "default",
  },
  background: {
    type: "starfield",
    color1: "#a855f7",
    color2: "#7c3aed",
    color3: "#c084fc",
    imageUrl: "",
    videoUrl: "",
    speed: 0.4,
    density: 1.4,
    size: 2,
    direction: "down",
    glow: true,
    blur: 0,
  },
  effects: {
    cursor: {
      enabled: true,
      type: "dots",
      color: "#c084fc",
      size: 5,
      fade: 0.1,
      followLag: 0.1,
      url: "",
    },
    click: {
      enabled: false,
      type: "none",
      emoji: "✨",
      color: "#c084fc",
      count: 8,
    },
    tilt3d: false,
    tiltIntensity: 12,
    typewriterTitle: false,
    glowPulse: false,
    textGlow: true,
    usernameEffect: "glow",
    animatedTitle: false,
    animatedTitleText: "",
  },
  splash: {
    enabled: true,
    type: "blur",
    text: "brazy",
    subtext: "click to enter",
    cta: "enter",
    blurAmount: 14,
    bgColor: "#08070d",
    textColor: "#e9d5ff",
    accentColor: "#c084fc",
    imageUrl: "",
    showEnterButton: false,
    duration: 0,
    enterSoundUrl: "",
  },
  audio: {
    enabled: true,
    src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    title: "midnight drive",
    artist: "brazy.fm",
    volume: 0.45,
    loop: true,
    autoplay: true,
    showVisualizer: true,
    style: "pill",
    trackId: "",
    coverUrl: "",
    lyrics: [],
  },
  social: {
    links: [
      { platform: "discord", url: "https://discord.gg/brazy", label: "discord", color: "#5865F2" },
      { platform: "twitter", url: "https://x.com/brazy", label: "x", color: "#e9d5ff" },
      { platform: "instagram", url: "https://instagram.com/brazy", label: "instagram", color: "#E4405F" },
      { platform: "spotify", url: "https://open.spotify.com", label: "spotify", color: "#1DB954" },
      { platform: "github", url: "https://github.com/brazy", label: "github", color: "#e9d5ff" },
      { platform: "tiktok", url: "https://tiktok.com/@brazy", label: "tiktok", color: "#e9d5ff" },
    ],
    layout: "wrap",
    size: "md",
    shape: "circle",
    showLabels: false,
    hoverEffect: true,
  },
  badges: {
    enabled: false,
    items: [],
    position: "top",
  },
  skills: {
    enabled: false,
    items: [],
  },
  projects: {
    enabled: false,
    items: [],
  },
  sections: {
    order: [
      "avatar", "name", "identity", "bio", "badges",
      "social", "audio", "discord", "views", "skills", "projects", "customHtml"
    ],
    visibility: {},
  },
  widgets: {
    discordPresence: { enabled: false, discordId: "", placement: "card", compact: false, showBackground: true, themeSync: true },
    youtube: { enabled: false, url: "", placement: "bottom", compact: false, showBackground: true, themeSync: true },
    github: { enabled: false, username: "", placement: "bottom", compact: false, showBackground: true, themeSync: true },
    time: { enabled: false, timezone: "UTC", format: "12h", placement: "card", compact: false, showBackground: true, themeSync: true },
    spotify: { enabled: false, url: "", placement: "card", compact: false, showBackground: true, themeSync: true },
    telegram: { enabled: false, username: "", text: "Join my Telegram channel!", placement: "card", compact: false, showBackground: true, themeSync: true },
  },
  customCss: "",
  customHtml: "",
  seo: {
    title: "brazy — one link, infinite vibes",
    description: "the most customizable bio on the internet.",
    ogImage: "",
  },
  analytics: {
    trackViews: true,
    showViews: true,
    viewsPlacement: "inside",
  },
};
