import type { ProfileConfig } from "./schema";

export const brazyProfile: ProfileConfig = {
  version: 1,
  identity: {
    username: "brazy",
    displayName: "brazy",
    bio: "building the most customizable bio on the internet. one link. infinite vibes.",
    avatarUrl: "https://i.pravatar.cc/300?u=brazy",
    tagline: "founder • designer • dreamer",
    pronouns: "they/them",
    location: "brazy.it",
    verified: true,
  },
  theme: {
    mode: "dark",
    primaryColor: "#8b5cf6",
    secondaryColor: "#ec4899",
    accentColor: "#22d3ee",
    textColor: "#f8fafc",
    mutedTextColor: "#94a3b8",
    backgroundColor: "#08070d",
    fontFamily: "geist",
    fontFamilyUrl: "",
    cardStyle: "glass",
    cardOpacity: 0.5,
    cardBlur: 22,
    borderRadius: 28,
    borderWidth: 1,
    glow: true,
    glowIntensity: 70,
    maxWidth: 540,
    contentAlign: "center",
    backgroundImage: "",
    backgroundOverlayColor: "#000000",
    backgroundOverlayOpacity: 0.4,
  },
  background: {
    type: "particles",
    color1: "#8b5cf6",
    color2: "#22d3ee",
    color3: "#ec4899",
    imageUrl: "",
    videoUrl: "",
    speed: 0.8,
    density: 1.2,
    size: 3,
    direction: "down",
    glow: true,
  },
  effects: {
    cursor: {
      enabled: true,
      type: "sparkles",
      color: "#22d3ee",
      size: 7,
      fade: 0.14,
      followLag: 0.2,
    },
    click: {
      enabled: true,
      type: "burst",
      emoji: "✨",
      color: "#ec4899",
      count: 14,
    },
    tilt3d: true,
    typewriterTitle: false,
    glowPulse: true,
    textGlow: true,
  },
  splash: {
    enabled: true,
    type: "blur",
    text: "brazy.it",
    subtext: "tap to enter",
    cta: "enter",
    blurAmount: 18,
    bgColor: "#08070d",
    textColor: "#f8fafc",
    accentColor: "#22d3ee",
    imageUrl: "",
    showEnterButton: false,
    duration: 0,
  },
  audio: {
    enabled: true,
    src: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    title: "midnight drive",
    artist: "brazy.fm",
    volume: 0.55,
    loop: true,
    autoplay: true,
    showVisualizer: true,
    style: "pill",
  },
  social: {
    links: [
      { platform: "discord", url: "https://discord.gg/brazy", label: "discord", color: "#5865F2" },
      { platform: "twitter", url: "https://x.com/brazy", label: "x", color: "#ffffff" },
      { platform: "instagram", url: "https://instagram.com/brazy", label: "instagram", color: "#E1306C" },
      { platform: "tiktok", url: "https://tiktok.com/@brazy", label: "tiktok", color: "#ffffff" },
      { platform: "spotify", url: "https://open.spotify.com", label: "spotify", color: "#1DB954" },
      { platform: "github", url: "https://github.com/brazy", label: "github", color: "#ffffff" },
      { platform: "website", url: "https://brazy.it", label: "brazy.it", color: "#22d3ee" },
    ],
    layout: "wrap",
    size: "md",
    shape: "circle",
    showLabels: false,
    hoverEffect: true,
  },
  badges: {
    enabled: true,
    items: [
      { label: "founder", emoji: "👑", color: "#fbbf24", tooltip: "brazy.it founder" },
      { label: "early", emoji: "🚀", color: "#22d3ee", tooltip: "early adopter" },
      { label: "verified", emoji: "✅", color: "#8b5cf6", tooltip: "verified human" },
    ],
    position: "top",
  },
  customCss: "",
  customHtml: "",
  seo: {
    title: "brazy — one link, infinite vibes",
    description: "the most customizable bio on the internet.",
    ogImage: "",
  },
  analytics: {
    trackViews: true,
  },
};
