import type { ProfileConfig } from "./schema";

export const emptyProfile: ProfileConfig = {
  version: 1,
  identity: {
    username: "",
    displayName: "",
    bio: "",
    avatarUrl: "",
    tagline: "",
    pronouns: "",
    location: "",
    verified: false,
    bioMarkdown: false,
  },
  theme: {
    mode: "dark",
    primaryColor: "#a855f7",
    secondaryColor: "#7c3aed",
    accentColor: "#c084fc",
    textColor: "#e9d5ff",
    mutedTextColor: "#71717a",
    backgroundColor: "#08070d",
    fontFamily: "geist",
    fontFamilyUrl: "",
    cardStyle: "glass",
    cardOpacity: 0.4,
    cardBlur: 20,
    borderRadius: 22,
    borderWidth: 1,
    glow: true,
    glowIntensity: 40,
    maxWidth: 440,
    contentAlign: "center",
    backgroundImage: "",
    backgroundOverlayColor: "#000000",
    backgroundOverlayOpacity: 0.5,
    animatedBorder: false,
    motionProfile: "balanced",
    profileSize: "default",
  },
  background: {
    type: "none",
    color1: "#a855f7",
    color2: "#7c3aed",
    color3: "#c084fc",
    imageUrl: "",
    videoUrl: "",
    speed: 0.4,
    density: 1.4,
    size: 2,
    direction: "down",
    glow: true,
    blur: 0,
  },
  effects: {
    cursor: {
      enabled: false,
      type: "none",
      color: "#a855f7",
      size: 20,
      fade: 0.12,
      followLag: 0.18,
      url: "",
    },
    click: {
      enabled: false,
      type: "none",
      emoji: "✨",
      color: "#a855f7",
      count: 8,
    },
    tilt3d: false,
    tiltIntensity: 0,
    typewriterTitle: false,
    glowPulse: false,
    textGlow: false,
    usernameEffect: "none",
    animatedTitle: false,
    animatedTitleText: "",
  },
  splash: {
    enabled: false,
    type: "blur",
    text: "",
    subtext: "",
    cta: "",
    blurAmount: 0,
    bgColor: "#08070d",
    textColor: "#f8fafc",
    accentColor: "#22d3ee",
    imageUrl: "",
    showEnterButton: false,
    duration: 0,
    enterSoundUrl: "",
  },
  audio: {
    enabled: false,
    src: "",
    title: "",
    artist: "",
    volume: 0.5,
    loop: false,
    autoplay: false,
    showVisualizer: false,
    style: "minimal" as const,
    trackId: "",
    coverUrl: "",
    lyrics: [],
    lyricsRaw: "",
    lyricsEnabled: false,
    lyricsSource: "none" as const,
  },
  social: {
    links: [],
    layout: "wrap",
    size: "md",
    shape: "rounded",
    showLabels: false,
    hoverEffect: true,
  },
  badges: {
    enabled: true,
    items: [],
    position: "top" as const,
  },
  skills: {
    enabled: false,
    items: [],
  },
  projects: {
    enabled: false,
    items: [],
  },
  sections: {
    order: [
      "avatar", "name", "identity", "bio", "badges",
      "social", "audio", "discord", "views", "skills", "projects", "customHtml"
    ],
    visibility: {},
  },
  widgets: {
    discordPresence: {
      enabled: false,
      placement: "card",
      compact: false,
      showBackground: true,
      themeSync: true,
      discordId: "",
    },
    youtube: {
      enabled: false,
      placement: "card",
      compact: false,
      showBackground: true,
      themeSync: true,
      url: "",
    },
    github: {
      enabled: false,
      placement: "card",
      compact: false,
      showBackground: true,
      themeSync: true,
      username: "",
    },
    time: {
      enabled: false,
      placement: "card",
      compact: false,
      showBackground: true,
      themeSync: true,
      timezone: "",
      format: "12h",
    },
    spotify: {
      enabled: false,
      placement: "card",
      compact: false,
      showBackground: true,
      themeSync: true,
      url: "",
    },
    telegram: {
      enabled: false,
      placement: "card",
      compact: false,
      showBackground: true,
      themeSync: true,
      username: "",
      text: "",
    },
  },
  customCss: "",
  customHtml: "",
  seo: {
    title: "",
    description: "",
    ogImage: "",
  },
  analytics: {
    trackViews: true,
    showViews: false,
    viewsPlacement: "none",
  },
};