import type { ProfileConfig } from "./schema";

export const emptyProfile: ProfileConfig = {
  version: 1,
  identity: {
    username: "",
    displayName: "",
    bio: "",
    avatarUrl: "",
    tagline: "",
    pronouns: "",
    location: "",
    verified: false,
    bioMarkdown: false,
  },
  theme: {
    mode: "dark",
    primaryColor: "#a855f7",
    secondaryColor: "#7c3aed",
    accentColor: "#c084fc",
    textColor: "#e9d5ff",
    mutedTextColor: "#71717a",
    backgroundColor: "#08070d",
    fontFamily: "geist",
    fontFamilyUrl: "",
    cardStyle: "glass",
    cardOpacity: 0.4,
    cardBlur: 20,
    borderRadius: 22,
    borderWidth: 1,
    glow: true,
    glowIntensity: 40,
    maxWidth: 440,
    contentAlign: "center",
    backgroundImage: "",
    backgroundOverlayColor: "#000000",
    backgroundOverlayOpacity: 0.5,
    animatedBorder: false,
    motionProfile: "balanced",
    profileSize: "default",
  },
  background: {
    type: "none",
    color1: "#a855f7",
    color2: "#7c3aed",
    color3: "#c084fc",
    imageUrl: "",
    videoUrl: "",
    speed: 0.4,
    density: 1.4,
    particleColor: "#a855f7",
    particleSize: 2,
    particleCount: 80,
    starColor: "#ffffff",
    starCount: 200,
    starSpeed: 0.5,
    matrixColor: "#00ff41",
    matrixSpeed: 1,
    matrixDensity: 0.05,
    auroraColor1: "#00ff88",
    auroraColor2: "#00aaff",
    auroraSpeed: 0.5,
    auroraComplexity: 3,
    rainColor: "#aaccff",
    rainSpeed: 1,
    rainDensity: 0.5,
    snowColor: "#ffffff",
    snowSpeed: 0.5,
    snowDensity: 0.5,
    bubbleColor: "#a855f7",
    bubbleSpeed: 0.5,
    bubbleDensity: 0.5,
    gridColor: "#a855f7",
    gridSize: 40,
    gridOpacity: 0.1,
  },
  effects: {
    cursor: {
      enabled: false,
      type: "none",
      color: "#a855f7",
      size: 20,
      customUrl: "",
    },
    click: {
      enabled: false,
      type: "none",
      color: "#a855f7",
      size: 20,
    },
    usernameEffect: "none",
    typewriterTitle: false,
    textGlow: false,
  },
  social: {
    hoverEffect: true,
    layout: "list",
    shape: "rounded",
    size: "md",
    links: [],
  },
  audio: {
    enabled: false,
    src: "",
    title: "",
    artist: "",
    coverUrl: "",
    volume: 0.5,
    autoplay: false,
    loop: false,
    lyrics: [],
  },
  badges: {
    enabled: true,
    items: [],
  },
  skills: {
    enabled: false,
    items: [],
  },
  projects: {
    enabled: false,
    items: [],
  },
  widgets: {
    discordPresence: {
      enabled: false,
      placement: "card",
      compact: false,
      showBackground: true,
      themeSync: true,
      discordId: "",
    },
    youtube: {
      enabled: false,
      placement: "card",
      compact: false,
      showBackground: true,
      themeSync: true,
      url: "",
    },
    github: {
      enabled: false,
      placement: "card",
      compact: false,
      showBackground: true,
      themeSync: true,
      username: "",
    },
    time: {
      enabled: false,
      placement: "card",
      compact: false,
      showBackground: true,
      themeSync: true,
      timezone: "",
      format: "12h",
    },
    spotify: {
      enabled: false,
      placement: "card",
      compact: false,
      showBackground: true,
      themeSync: true,
      url: "",
    },
    telegram: {
      enabled: false,
      placement: "card",
      compact: false,
      showBackground: true,
      themeSync: true,
      username: "",
      text: "",
    },
  },
  analytics: {
    showViews: false,
    viewsPlacement: "none",
  },
  splash: {
    enabled: false,
    text: "",
    duration: 2000,
    backgroundColor: "#000000",
    textColor: "#ffffff",
  },
  customCss: "",
  customHtml: "",
};